spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    username: root
    password: gcj
    #时区设置： serverTimezone=XXX 和mysql版本有关，较高版本的mysql需要设置时区
    url: jdbc:mysql://localhost:3306/bbs?serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8080

#整合mybatis
mybatis:
  type-aliases-package: com.yujian.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
img:
  location: C:\Users\Administrator\Desktop\专业实训\bbs\src\main\resources\static\upload
